#ifndef ERRDEF_H_
#define ERRDEF_H_

#define GAZE_OK 0

#define GAZE_ETH_FAIL -100
#define GAZE_ETH_NOT_SUPPORT -101

#define GAZE_IP_FAIL -200
#define GAZE_IP_NOT_SUPPORT -201
#define GAZE_IP_NOT_V4 -202
#define GAZE_IP_WITH_OPTION -203
#define GAZE_IP_CHECKSUM_ERROR -204
#define GAZE_IP_MF_NOT_SUPPORT -205

#define GAZE_TCP_FAIL -300
#define GAZE_TCP_CHECKSUM_ERROR -301
#define GAZE_TCP_OPTION_FAIL -302
#define GAZE_TCP_LINK_FAIL -303

#endif
